# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98d6c37d611f056f5c22577dc4ac9deb75e624bf5b4f70e68568c39924a34824e4b381712cd2450e9ec00f6b8ea3d75ff5e4a6daefb42d04d6e1b9206949b6a7

test:
  secret_key_base: 9cbffce81f075cbc95bf23d27c5910938c2b12e6d1487153c0748e39d4316f691af7f7e262ff82816570f89b25171e6ff911a6519f23dbcbb2891025b833bb90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
